//! Article heading rule — single source of truth for the auto-injected
//! `<h1 class="moss-article-title">` and the editor's pinned filename heading.
//!
//! Both consumers — the build pipeline (`src-tauri/src/build/markdown/pipeline.rs`)
//! and the editor command `compute_heading_state`
//! (`src-tauri/src/editor/commands.rs`) — feed the same inputs into [`compute`]
//! and act on the same answer. Without this module the two paths silently
//! desync the next time the rule changes (new opt-out, new index pattern,
//! hero-H1 detection, ...).
//!
//! The rule:
//!   - Markdown files only.
//!   - Index/folder pages never get the auto-injected H1.
//!   - Frontmatter `heading: false` opts out (`Some(true)`/`None`/missing show).
//!   - A hero block that already contains an `<h1>` owns the title slot.
//!
//! The visible text is the title-cased filename (folder notes use the parent
//! folder name). See `docs/architecture/title-rendering.md`.

use crate::home;

/// Resolved heading state for a single page.
///
/// `visible` is the gate the build pipeline checks before injecting an
/// `<h1 class="moss-article-title">` and the editor checks before rendering
/// its pinned filename heading element.
#[cfg_attr(feature = "specta", derive(specta::Type))]
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct HeadingState {
    /// Whether the article heading should render.
    pub visible: bool,
    /// The visible heading text (filename, hyphens/underscores → spaces,
    /// folder-note → parent folder name).
    pub text: String,
}

/// Inputs to the heading rule.
///
/// Callers populate as much as they have. The editor command knows the file
/// path and the `heading` field; the build pipeline additionally knows the
/// rendered hero HTML and whether this file is a translation-home override.
#[derive(Debug, Clone, Copy)]
pub struct HeadingInputs<'a> {
    pub file_path: &'a str,
    /// Frontmatter `heading` field. `Some(false)` opts out; `Some(true)`,
    /// `None`, and missing all mean "show".
    pub heading_field: Option<bool>,
    /// Pipeline-only input: pre-rendered hero HTML. When it contains an
    /// `<h1>` tag the hero owns the title slot and the article heading is
    /// hidden. The editor passes `None` and accepts the narrow inconsistency
    /// (no shortcode pipeline at edit time). See issue #609 follow-ups.
    pub hero_html: Option<&'a str>,
    /// Pipeline-only input: `true` iff the file is promoted to its folder's
    /// home via `translationKey: home` (issue #587). Pipeline derives from
    /// `page_map`; the editor passes `false` (no built page_map at edit
    /// time). The filename-only home detection runs internally; this flag
    /// is the page_map-only override.
    pub is_translation_home: bool,
}

/// Compute just the visible heading text for a file path.
///
/// Used by callers that need the text before all visibility inputs are
/// available (e.g. the build pipeline computes `filename_title` early to
/// feed downstream label fallback). [`compute`] uses the same logic.
pub fn filename_text(file_path: &str) -> String {
    let path = std::path::Path::new(file_path);
    let stem = path
        .file_stem()
        .and_then(|s| s.to_str())
        .unwrap_or("Untitled");
    let parent_name = path
        .parent()
        .and_then(|p| p.file_name())
        .and_then(|s| s.to_str());
    let is_folder_note = home::is_index_stem(stem)
        || parent_name.is_some_and(|p| p.eq_ignore_ascii_case(stem));
    let source_name = if is_folder_note {
        parent_name.unwrap_or(stem)
    } else {
        stem
    };
    source_name.replace('-', " ").replace('_', " ")
}

/// Compute the full heading state (visible + text) for a page.
pub fn compute(input: HeadingInputs<'_>) -> HeadingState {
    let path = std::path::Path::new(input.file_path);

    let text = filename_text(input.file_path);

    let is_markdown = matches!(
        path.extension()
            .and_then(|e| e.to_str())
            .map(|s| s.to_lowercase())
            .as_deref(),
        Some("md") | Some("mdx") | Some("markdown")
    );

    let stem = path.file_stem().and_then(|s| s.to_str()).unwrap_or("");
    let parent_name = path
        .parent()
        .and_then(|p| p.file_name())
        .and_then(|s| s.to_str())
        .unwrap_or("");
    let filename_lower = stem.to_lowercase();
    let is_index_file =
        home::is_home_file(&filename_lower, parent_name) || input.is_translation_home;

    let opted_out = input.heading_field == Some(false);
    let hero_owns_title = hero_contains_h1(input.hero_html);

    let visible = is_markdown && !is_index_file && !opted_out && !hero_owns_title;

    HeadingState { visible, text }
}

/// Whether a hero HTML block contains an `<h1>` tag.
///
/// Substring match — sufficient because hero HTML is generated by the
/// shortcode renderer, never user-pasted, so there is no stray `<h1` token
/// to misclassify.
fn hero_contains_h1(hero_html: Option<&str>) -> bool {
    hero_html.is_some_and(|h| h.contains("<h1"))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn inputs(file_path: &str, heading_field: Option<bool>) -> HeadingInputs<'_> {
        HeadingInputs {
            file_path,
            heading_field,
            hero_html: None,
            is_translation_home: false,
        }
    }

    // ── filename_text ────────────────────────────────────────────────

    #[test]
    fn text_article_uses_filename() {
        assert_eq!(filename_text("posts/my-first-post.md"), "my first post");
    }

    #[test]
    fn text_underscore_normalizes_to_space() {
        assert_eq!(filename_text("posts/my_first_post.md"), "my first post");
    }

    #[test]
    fn text_index_uses_parent_folder() {
        assert_eq!(filename_text("site/index.md"), "site");
    }

    #[test]
    fn text_readme_uses_parent_folder() {
        assert_eq!(filename_text("docs/README.md"), "docs");
    }

    #[test]
    fn text_self_named_folder_note_uses_parent() {
        assert_eq!(filename_text("recipes/recipes.md"), "recipes");
    }

    #[test]
    fn text_root_level_no_parent() {
        assert_eq!(filename_text("about.md"), "about");
    }

    #[test]
    fn text_cjk_filename_preserved() {
        assert_eq!(filename_text("文字/民歌.md"), "民歌");
    }

    #[test]
    fn text_cjk_index_uses_parent() {
        assert_eq!(filename_text("文字/index.md"), "文字");
    }

    // ── compute: visibility ──────────────────────────────────────────

    #[test]
    fn visible_for_article_md() {
        let s = compute(inputs("posts/my-first-post.md", None));
        assert!(s.visible);
        assert_eq!(s.text, "my first post");
    }

    #[test]
    fn hidden_for_index_file() {
        let s = compute(inputs("site/index.md", None));
        assert!(!s.visible);
        assert_eq!(s.text, "site");
    }

    #[test]
    fn hidden_for_readme() {
        let s = compute(inputs("docs/README.md", None));
        assert!(!s.visible);
        assert_eq!(s.text, "docs");
    }

    #[test]
    fn hidden_for_self_named_folder_note() {
        let s = compute(inputs("recipes/recipes.md", None));
        assert!(!s.visible);
        assert_eq!(s.text, "recipes");
    }

    #[test]
    fn hidden_when_heading_false() {
        let s = compute(inputs("posts/article.md", Some(false)));
        assert!(!s.visible);
    }

    #[test]
    fn visible_when_heading_true() {
        let s = compute(inputs("posts/article.md", Some(true)));
        assert!(s.visible);
    }

    #[test]
    fn visible_when_heading_missing() {
        // None mirrors `Option<bool>::None` on the typed pipeline side and
        // YAML `null`/missing-key on the JSON-typed editor side.
        let s = compute(inputs("posts/article.md", None));
        assert!(s.visible);
    }

    #[test]
    fn hidden_for_non_markdown() {
        let s = compute(inputs("assets/style.css", None));
        assert!(!s.visible);
    }

    #[test]
    fn visible_for_mdx() {
        let s = compute(inputs("posts/article.mdx", None));
        assert!(s.visible);
        assert_eq!(s.text, "article");
    }

    #[test]
    fn visible_for_root_level_article() {
        let s = compute(inputs("about.md", None));
        assert!(s.visible);
        assert_eq!(s.text, "about");
    }

    #[test]
    fn visible_for_cjk_article() {
        let s = compute(inputs("文字/民歌.md", None));
        assert!(s.visible);
        assert_eq!(s.text, "民歌");
    }

    #[test]
    fn hidden_for_cjk_index() {
        let s = compute(inputs("文字/index.md", None));
        assert!(!s.visible);
        assert_eq!(s.text, "文字");
    }

    // ── compute: hero-H1 gate ────────────────────────────────────────

    #[test]
    fn hidden_when_hero_has_h1() {
        let s = compute(HeadingInputs {
            file_path: "posts/article.md",
            heading_field: None,
            hero_html: Some("<header><h1>Hero title</h1></header>"),
            is_translation_home: false,
        });
        assert!(!s.visible, "hero owns the title slot when it contains an <h1>");
    }

    #[test]
    fn visible_when_hero_has_no_h1() {
        let s = compute(HeadingInputs {
            file_path: "posts/article.md",
            heading_field: None,
            hero_html: Some("<header><h2>Sub</h2></header>"),
            is_translation_home: false,
        });
        assert!(s.visible);
    }

    #[test]
    fn visible_when_no_hero() {
        let s = compute(HeadingInputs {
            file_path: "posts/article.md",
            heading_field: None,
            hero_html: None,
            is_translation_home: false,
        });
        assert!(s.visible);
    }

    #[test]
    fn hidden_when_hero_h1_has_attributes() {
        let s = compute(HeadingInputs {
            file_path: "posts/article.md",
            heading_field: None,
            hero_html: Some("<section><h1 id=\"x\" class=\"y\">Hero</h1></section>"),
            is_translation_home: false,
        });
        assert!(!s.visible);
    }

    // ── compute: translation-home override ───────────────────────────

    #[test]
    fn hidden_when_translation_home() {
        let s = compute(HeadingInputs {
            file_path: "posts/article.md",
            heading_field: None,
            hero_html: None,
            is_translation_home: true,
        });
        assert!(!s.visible, "translation-home overrides treat the page as an index");
    }
}
